# Generated by Django 3.2 on 2021-05-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_alter_construction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Deleted')], default=1, verbose_name='Status'),
        ),
    ]
