# Generated by Django 3.2 on 2021-05-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_construction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
    ]
