# Generated by Django 3.2 on 2021-06-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_auto_20210608_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructions', to='construction.object', verbose_name='Object'),
        ),
    ]
