# Generated by Django 3.2 on 2021-07-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_alter_construction_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='construction',
            options={'ordering': ('name',), 'verbose_name': 'Construction', 'verbose_name_plural': 'Constructions'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ('name',), 'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
    ]
