# Generated by Django 3.2 on 2021-07-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction', '0008_auto_20210709_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Device name')),
                ('ipaddress', models.CharField(help_text='write there ip address', max_length=17, verbose_name='IP address')),
                ('log', models.IntegerField(choices=[(0, 'in'), (1, 'out')], verbose_name='checking')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.construction', verbose_name='Construction')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminals',
            },
        ),
    ]
