# Generated by Django 3.2 on 2021-07-13 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_auto_20210709_1113'),
        ('terminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('employee_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='male', max_length=50, verbose_name='Gender')),
                ('birthday', models.DateField(verbose_name='Birthday date')),
                ('enable', models.BooleanField(default=True, verbose_name='Enable')),
                ('begin_time', models.DateTimeField(verbose_name='Begin Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('verify_mode', models.CharField(choices=[('card', 'Card'), ('faceAndCard', 'Face and Card (both)'), ('face', 'Face'), ('cardOrFace', 'Card or Password (anyone)')], default='face', max_length=50, verbose_name='Verify mode')),
            ],
            options={
                'verbose_name': 'Door',
                'verbose_name_plural': 'Doors',
            },
        ),
        migrations.AlterField(
            model_name='terminal',
            name='construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.construction', verbose_name='Construction'),
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('image', models.ImageField(help_text='there is the face picture URL (not a file)', upload_to='', verbose_name='Face image url')),
                ('face_lib', models.CharField(default='blackFD', max_length=50, verbose_name='Face library type')),
                ('face_data_id', models.CharField(default='1', editable=False, max_length=63)),
                ('face_person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.person', verbose_name='Person ID')),
            ],
            options={
                'verbose_name': 'Face',
                'verbose_name_plural': 'Faces',
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Door name')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.construction', verbose_name='Construction')),
            ],
            options={
                'verbose_name': 'Door',
                'verbose_name_plural': 'Doors',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('card_number', models.CharField(max_length=50, verbose_name='Card number')),
                ('card_type', models.CharField(choices=[('normalCard', 'Normal Card')], default='normalCard', max_length=20, verbose_name='Card type')),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.person', verbose_name='Employee ID')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.AddField(
            model_name='terminal',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminal.door', verbose_name='Construction'),
        ),
    ]
