# Generated by Django 3.2 on 2021-07-13 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0003_auto_20210714_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='direction',
            field=models.CharField(choices=[(0, 'Login'), (1, 'Logout')], default=django.utils.timezone.now, max_length=20, verbose_name='Door direction'),
            preserve_default=False,
        ),
    ]
