# Generated by Django 3.2 on 2021-07-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_alter_door_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminal.door', verbose_name='Door'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='log',
            field=models.IntegerField(choices=[(0, 'login'), (1, 'logout')], verbose_name='checking'),
        ),
    ]
