# Generated by Django 3.2 on 2021-07-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_auto_20210714_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='terminal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='terminal.terminal', verbose_name='Terminal'),
        ),
    ]
