# Generated by Django 3.2 on 2021-07-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0008_auto_20210714_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='verify_mode',
            field=models.CharField(choices=[('card', 'Card'), ('faceAndCard', 'Face and Card (both)'), ('face', 'Face'), ('cardOrFace', 'Card or Face (anyone)')], default='face', max_length=50, verbose_name='Verify mode'),
        ),
    ]
