# Generated by Django 3.2 on 2021-07-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('name',), 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
    ]
