# Generated by Django 3.2 on 2021-05-05 05:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('image', models.ImageField(upload_to='media/header_workers', verbose_name='Profile image')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone Number')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='headerworkers', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Header worker',
                'verbose_name_plural': 'Header workers',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Position name')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description position')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='SubWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('image', models.ImageField(upload_to='media/header_workers', verbose_name='Profile image')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone Number')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subworkers', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
                ('header_worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.headerworker', verbose_name='Header worker')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.position', verbose_name='worker position')),
            ],
            options={
                'verbose_name': 'Sub worker',
                'verbose_name_plural': 'Sub workers',
            },
        ),
        migrations.AddField(
            model_name='headerworker',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.position', verbose_name='worker position'),
        ),
    ]
