# Generated by Django 3.2 on 2021-05-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210505_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(db_index=True, max_length=50, null=True, unique=True, verbose_name='Email'),
        ),
    ]
