# Generated by Django 3.2 on 2021-05-05 08:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_alter_construction_description'),
        ('account', '0005_alter_account_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerworker',
            options={'verbose_name': 'Header worker', 'verbose_name_plural': ' Header workers'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Position', 'verbose_name_plural': '   Positions'},
        ),
        migrations.AlterModelOptions(
            name='subworker',
            options={'verbose_name': 'Sub worker', 'verbose_name_plural': '  Sub workers'},
        ),
        migrations.AddField(
            model_name='headerworker',
            name='construction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.construction', verbose_name='Construction'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description position'),
        ),
    ]
