# Generated by Django 3.2 on 2021-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210505_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerworker',
            name='dismissed',
            field=models.BooleanField(default=False, verbose_name='Dismissed'),
        ),
        migrations.AddField(
            model_name='subworker',
            name='dismissed',
            field=models.BooleanField(default=False, verbose_name='Dismissed'),
        ),
        migrations.AlterField(
            model_name='headerworker',
            name='image',
            field=models.ImageField(upload_to='header_workers/profile_image', verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='subworker',
            name='image',
            field=models.ImageField(upload_to='sub_workers/profile_image', verbose_name='Profile image'),
        ),
    ]
