# Generated by Django 3.2 on 2021-05-05 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210505_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('image', models.ImageField(upload_to='sub_workers/profile_image', verbose_name='Profile image')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone Number')),
                ('path', models.TextField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('dismissed', models.BooleanField(default=False, verbose_name='Dismissed')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to=settings.AUTH_USER_MODEL, verbose_name='Account')),
                ('header_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='account.worker')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.position', verbose_name='worker position')),
            ],
            options={
                'verbose_name': 'Sub worker',
                'verbose_name_plural': ' Sub workers',
            },
        ),
    ]
