# Generated by Django 3.2 on 2021-05-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_worker_construction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': ' Workers'},
        ),
        migrations.AddField(
            model_name='worker',
            name='header',
            field=models.BooleanField(default=False, verbose_name='Is Header'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='dismissed',
            field=models.BooleanField(default=False, verbose_name='Is Dismissed'),
        ),
    ]
