# Generated by Django 3.2 on 2021-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210506_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(upload_to='workers/profile_image', verbose_name='Profile image'),
        ),
    ]
