# Generated by Django 3.2 on 2021-05-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_alter_construction_description'),
        ('account', '0014_alter_worker_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.construction', verbose_name='Construction'),
        ),
    ]
