# Generated by Django 3.2 on 2021-05-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_worker_construction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='dismissed',
            new_name='is_dismissed',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='header',
            new_name='is_header',
        ),
    ]
