# Generated by Django 3.2 on 2021-05-17 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210506_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='path',
        ),
        migrations.AlterField(
            model_name='worker',
            name='header_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_header': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='account.worker'),
        ),
    ]
