# Generated by Django 3.2 on 2021-05-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_worker_header_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='header_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_header': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='account.worker'),
        ),
    ]
