# Generated by Django 3.2 on 2021-05-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_construction_status'),
        ('account', '0020_alter_worker_header_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Deleted')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='construction',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.construction', verbose_name='Construction'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.position', verbose_name='worker position'),
        ),
    ]
