# Generated by Django 3.2 on 2021-05-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_alter_construction_status'),
        ('account', '0021_auto_20210524_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='construction',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, to='construction.construction', verbose_name='Construction'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.position', verbose_name='worker position'),
        ),
    ]
