# Generated by Django 3.2 on 2021-05-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_alter_construction_status'),
        ('account', '0022_auto_20210524_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='construction',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_workers', to='construction.construction', verbose_name='Construction'),
        ),
    ]
