# Generated by Django 3.2 on 2021-06-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20210525_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='construction',
        ),
    ]
