# Generated by Django 3.2 on 2021-07-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_worker_construction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('last_name',), 'verbose_name': 'Worker', 'verbose_name_plural': ' Workers'},
        ),
    ]
