# Generated by Django 3.2 on 2021-07-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_worker_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subworker',
            name='account',
        ),
        migrations.RemoveField(
            model_name='subworker',
            name='header_worker',
        ),
        migrations.RemoveField(
            model_name='subworker',
            name='position',
        ),
        migrations.DeleteModel(
            name='HeaderWorker',
        ),
        migrations.DeleteModel(
            name='SubWorker',
        ),
    ]
