# Generated by Django 3.2 on 2021-05-17 09:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0017_auto_20210517_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField(blank=True, null=True, verbose_name='Check in time')),
                ('checkout', models.DateTimeField(blank=True, null=True, verbose_name='Check out time')),
                ('working_hours', models.FloatField(blank=True, null=True, verbose_name='Working hours')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('header_worker', models.ForeignKey(blank=True, limit_choices_to={'is_header': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='headerworkers', to='account.worker', verbose_name='Header Worker')),
                ('worker', models.ForeignKey(blank=True, limit_choices_to={'is_header': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subworkers', to='account.worker', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50, verbose_name='Reason')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Reason',
                'verbose_name_plural': 'Reasons',
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(verbose_name='Working hours')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
            ],
            options={
                'verbose_name': 'Working Hours',
                'verbose_name_plural': 'Working Hours',
            },
        ),
        migrations.CreateModel(
            name='ReasonToNoAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', ckeditor.fields.RichTextField(verbose_name='Context')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.attendance', verbose_name='Attendance')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.reason', verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Reason To No Attendance',
                'verbose_name_plural': 'Reason To No Attendances',
            },
        ),
    ]
