# Generated by Django 3.2 on 2021-05-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': '  Attendances'},
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'verbose_name': 'Reason', 'verbose_name_plural': '  Reasons'},
        ),
        migrations.AlterModelOptions(
            name='workinghour',
            options={'verbose_name': 'Working Hours', 'verbose_name_plural': '   Working Hours'},
        ),
        migrations.AlterField(
            model_name='reasontonoattendance',
            name='context',
            field=models.TextField(verbose_name='Context'),
        ),
    ]
