# Generated by Django 3.2 on 2021-05-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='working_hours',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Working hours'),
        ),
    ]
