# Generated by Django 3.2 on 2021-05-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='working_hours',
            field=models.FloatField(default=0, verbose_name='Working hours'),
        ),
    ]
