# Generated by Django 3.2 on 2021-06-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_auto_20210608_1643'),
        ('attendance', '0005_alter_attendance_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='construction',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 0}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_workers', to='construction.construction', verbose_name='Construction'),
        ),
    ]
