# Generated by Django 3.2 on 2021-06-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20210615_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='mark',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=4, verbose_name='Mark'),
        ),
    ]
