# Generated by Django 3.2 on 2021-06-18 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 5, 31, 53, 558219, tzinfo=utc), verbose_name='Created date'),
        ),
    ]
