# Generated by Django 3.2 on 2021-06-18 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendance_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date'),
        ),
    ]
